repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: backend
        name: backend-lint
        entry: ./ops/prettier.sh
        language: script
        files: ^src/new-backend/.*\.ts$
