version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /opt/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=testing
      - POSTGRES_USER=pguser
      - POSTGRES_DB=packetware