name: Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  protoc:
    runs-on: ubuntu-latest 
    steps:
      - name: Install direnv
        run: sudo apt-get update && sudo apt-get install -y direnv

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Generate gRPC code
        run: |
          eval "$(direnv export bash)"
          direnv reload
          cd src/backend
          protoc --go_out=. --go-grpc_out=. \
            --go_opt=paths=source_relative \
            --go-grpc_opt=paths=source_relative \
            -I . rpc/gen/all.proto

      - name: Check for differences
        run: |
          git diff --exit-code
