name: Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Install direnv
        run: sudo apt update && sudo apt install -y direnv
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Run the linter
        run: |
          curl -L https://nixos.org/nix/install | sh -s -- --no-daemon
          direnv allow
          eval "$(direnv export bash)"
          cd src/new-backend
          bun install
          bunx prettier --write .

      - name: Check for differences
        run: git diff --exit-code

  # protoc:
  # runs-on: ubuntu-latest
  #  steps:
  #    - name: Install direnv
  #      run: sudo apt-get update && sudo apt-get install -y direnv
  #
  #    - name: Check out code into the Go module directory
  #      uses: actions/checkout@v2
  #
  #  - name: Generate gRPC code
  #    run: |
  #      eval "$(direnv export bash)"
  #      direnv reload
  #      cd src/backend
  #      protoc --go_out=. --go-grpc_out=. \
  #        --go_opt=paths=source_relative \
  #        --go-grpc_opt=paths=source_relative \
  #        -I . rpc/gen/all.proto
  #
  #  - name: Check for differences
  #    run: |
  #      git diff --exit-code
