name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install pre-commit and dependencies
        run: |
          pip install pre-commit
          pre-commit install

      - name: Run pre-commit checks
        run: pre-commit run --all-files

  nancy-scan:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20' # specify your Go version

    - name: Install Nancy
      run: |
        curl -sSfL https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.32/nancy-linux.amd64-v1.0.32 | sudo tee /usr/local/bin/nancy > /dev/null && sudo chmod +x /usr/local/bin/nancy

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          # optional: you can cache your Go modules
          # ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install Go dependencies
      run: go mod download

    - name: Run Nancy
      run: go list -m all | nancy sleuth
