name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linter
        run: |
          eval "$(direnv export bash)"
          direnv reload
          cd src/frontend
          yarn install
          yarn run lint
        shell: bash

  yarn-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run linter
        run: |
          eval "$(direnv export bash)"
          direnv reload
          cd src/frontend
          yarn install
          yarn audit
        shell: bash
