name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2

      - name: Run the linter
        run: |
          cd src/new-backend
          bun install
          bunx prettier --write .
          bunx eslint .
        shell: bash

      - name: Check for differences
        run: git diff --exit-code
