name: Frontend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    runs-on: self-hosted

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: direnv load
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.1

      - name: Run pre-commit checks
        run: |
          cd src/frontend
          eslint --fix .
          git diff --exit-code

  nancy-scan:
    runs-on: npm audit

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: direnv load
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.1

      - name: npm audit
        run: |
          npm audit
          git diff --exit-code
