name: Opnieuw

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: direnv load
        run: direnv allow

      - name: Run pre-commit checks
        run: |
          direnv reload
          cd src/opnieuw
          cargo fmt
          git diff --exit-code

  clippy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: direnv load
        run: direnv allow

      - name: Run clippy
        run: |
          direnv reload
          cd src/opnieuw
          cargo clippy
