name: Opnieuw

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run fmt
        run: |
          eval "$(direnv export bash)"
          direnv reload
          cd src/opnieuw
          cargo fmt
          git diff --exit-code
        shell: bash

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run clippy
        run: |
          sudo apt install protobuf-compiler -y
          cd src/opnieuw
          cargo clippy
        shell: bash
