name: Opnieuw

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: direnv load
        run: direnv allow
        shell: bash

      - name: Run pre-commit checks
        run: |
          direnv reload
          cd src/opnieuw
          cargo fmt
          git diff --exit-code
        shell: bash

  clippy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: direnv load
        run: |
          echo 'eval "$(direnv hook bash)"' >> ~/.bashrc
          direnv allow
        shell: bash

      - name: Run clippy
        run: |
          eval "$(direnv export bash)"
          source ~/.bashrc
          direnv reload
          cd src/opnieuw
          cargo clippy
        shell: bash
