name: Opnieuw

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Rust nightly
        run: rustup default nightly

      - name: Run fmt
        working-directory: src/opnieuw
        run: cargo fmt
        shell: bash

      - name: Check for lint diffs
        run: git diff --exit-code

  clippy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run clippy
        working-directory: src/opnieuw
        run: |
          sudo apt install protobuf-compiler -y
          cargo clippy
        shell: bash
