name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.1

      - name: Run pre-commit
        run: pre-commit run -v --all-files
        shell: bash
