name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install direnv
        run: sudo apt-get update && sudo apt-get install -y direnv

      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pre-commit
        run: |
          eval "$(direnv export bash)"
          direnv reload
          pre-commit run --all-files
        shell: bash
