name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: self-hosted

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: direnv load
        uses: HatsuneMiku3939/direnv-action@v1
        with:
          direnvVersion: 2.32.1

      - name: Run pre-commit checks
        run: pre-commit run --all-files
