name: Pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pre-commit:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: direnv load
        run: direnv allow

      - name: Run pre-commit checks
        run: pre-commit run --all-files
